window.cditData = {
  courses: [
    {
      code: 'CEO',
      slug: 'certificate-in-electronic-office',
      name: 'Certificate in Electronic Office',
      duration: 3,
      durationLabel: '3 Months',
      categoryPrimary: 'Office Automation',
      categories: ['Certification', 'Office Automation', 'PSC Approved'],
      shortDescription: 'Learn practical office workflows, computer operations and digital productivity for everyday work.',
      description: 'This course helps learners build confidence in electronic office work, document preparation, practical productivity tasks and professional digital routines.',
      eligibility: 'Beginner friendly',
      level: 'Beginner',
      type: 'Certificate',
      image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80',
      featured: true,
      recommended: true,
      modules: ['Office productivity basics', 'Document handling and file management', 'Digital communication tasks', 'Practical office workflow exercises'],
      audience: ['Students', 'Office learners', 'Beginners'],
      progression: 'A suitable foundation for office work, digital skill courses and further study.'
    },
    {
      code: 'CDECO',
      slug: 'certificate-in-data-entry-and-console-operation',
      name: 'Certificate in Data Entry and Console Operation',
      duration: 3,
      durationLabel: '3 Months',
      categoryPrimary: 'Data Entry',
      categories: ['Certification', 'Data Entry', 'PSC Approved'],
      shortDescription: 'Build speed, accuracy and confidence in entering and managing data using office systems and consoles.',
      description: 'This certificate course develops efficient data entry habits, keyboard accuracy and console-based office tasks needed in clerical and administrative work.',
      eligibility: 'Basic computer familiarity helpful',
      level: 'Beginner',
      type: 'Certificate',
      image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
      featured: true,
      recommended: true,
      modules: ['Keyboard skills and speed practice', 'Console-based operations', 'Accuracy checks and data validation', 'Practical office data entry work'],
      audience: ['Students', 'Office aspirants', 'Career starters'],
      progression: 'Useful for clerical roles and continued office technology learning.'
    },
    {
      code: 'CMDP',
      slug: 'certificate-in-malayalam-computation-and-digital-publishing',
      name: 'Certificate in Malayalam Computation & Digital Publishing',
      duration: 2,
      durationLabel: '2 Months',
      categoryPrimary: 'Digital Publishing',
      categories: ['Certification', 'Digital Publishing', 'PSC Approved'],
      shortDescription: 'Develop Malayalam typing and basic digital publishing skills for office and document work.',
      description: 'This course introduces Malayalam computation, typing techniques and digital publishing basics needed for office communication and layout tasks.',
      eligibility: 'Suitable for learners with basic computer awareness',
      level: 'Beginner',
      type: 'Certificate',
      image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Malayalam typing and layout', 'Digital publishing workflow', 'Document formatting basics', 'Practical publishing exercises'],
      audience: ['Students', 'Office learners', 'Aspiring publishers'],
      progression: 'Useful before advanced design or publishing-based training.'
    },
    {
      code: 'CDTP',
      slug: 'certificate-in-desktop-publishing',
      name: 'Certificate in Desktop Publishing',
      duration: 3,
      durationLabel: '3 Months',
      categoryPrimary: 'Desktop Publishing',
      categories: ['Certification', 'Desktop Publishing', 'PSC Approved'],
      shortDescription: 'Learn page design, formatting and publishing skills for print and digital communication.',
      description: 'This certificate course gives learners practical knowledge in document design, formatting, publishing tools and visual communication for office and print use.',
      eligibility: 'Open to beginners',
      level: 'Beginner',
      type: 'Certificate',
      image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Page layout fundamentals', 'Document formatting', 'Publishing workflow and output', 'Practical design tasks'],
      audience: ['Students', 'Design learners', 'Office workers'],
      progression: 'A strong starting point for design, publishing and multimedia studies.'
    },
    {
      code: 'DDCFM',
      slug: 'diploma-in-computerised-finance-management',
      name: 'Diploma in Computerised Finance Management',
      duration: 6,
      durationLabel: '6 Months',
      categoryPrimary: 'Finance & Accounting',
      categories: ['Diploma', 'Finance & Accounting', 'PSC Approved', 'Recommended'],
      shortDescription: 'Study practical finance and accounting workflows using computer-based systems and business applications.',
      description: 'This diploma introduces computerised finance management, bookkeeping and practical accounting practices used in business and office environments.',
      eligibility: 'Suitable for learners with basic computer familiarity',
      level: 'Intermediate',
      type: 'Diploma',
      image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
      featured: true,
      recommended: true,
      modules: ['Accounting fundamentals', 'Financial record handling', 'Business reporting and documentation', 'Computerised finance operations'],
      audience: ['Students', 'Business learners', 'Job seekers'],
      progression: 'Useful for business, office and finance-related career paths.'
    },
    {
      code: 'DCA',
      slug: 'diploma-in-computer-application',
      name: 'Diploma in Computer Application',
      duration: 6,
      durationLabel: '6 Months',
      categoryPrimary: 'Computer Application',
      categories: ['Diploma', 'Computer Application', 'PSC Approved', 'Recommended'],
      shortDescription: 'Build practical digital and application skills for office work, documentation and everyday computer use.',
      description: 'This diploma gives learners strong foundations in software use, productivity tools and computer-based tasks for academic and professional growth.',
      eligibility: 'Beginner friendly',
      level: 'Beginner to Intermediate',
      type: 'Diploma',
      image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80',
      featured: true,
      recommended: true,
      modules: ['Computer fundamentals', 'Word processing and spreadsheets', 'Presentations and workplace tools', 'Practical digital tasks'],
      audience: ['Students', 'Beginners', 'Job seekers'],
      progression: 'A strong foundation for further digital studies and office-based roles.'
    },
    {
      code: 'DMM',
      slug: 'diploma-in-multimedia',
      name: 'Diploma in Multimedia',
      duration: 6,
      durationLabel: '6 Months',
      categoryPrimary: 'Multimedia',
      categories: ['Diploma', 'Multimedia', 'PSC Approved'],
      shortDescription: 'Explore multimedia design, visual content and digital storytelling for creative work.',
      description: 'This diploma develops understanding of multimedia tools, design concepts and practical digital content production for visual communication.',
      eligibility: 'Open to learners interested in creative digital work',
      level: 'Beginner',
      type: 'Diploma',
      image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Multimedia essentials', 'Visual design basics', 'Creative project development', 'Digital communication and presentation'],
      audience: ['Creative learners', 'Students', 'Design beginners'],
      progression: 'Useful for creative digital careers and design-focused learning paths.'
    },
    {
      code: 'PGDCA',
      slug: 'postgraduate-diploma-in-computer-application',
      name: 'Postgraduate Diploma in Computer Application',
      duration: 12,
      durationLabel: '12 Months',
      categoryPrimary: 'Computer Application',
      categories: ['Diploma', 'Computer Application', 'PSC Approved'],
      shortDescription: 'Advance your computer application knowledge with a broader, practice-focused digital learning path.',
      description: 'This postgraduate diploma covers deeper digital application skills, productivity workflows and practical problem-solving for serious learners.',
      eligibility: 'Intermediate familiarity with computer use recommended',
      level: 'Intermediate',
      type: 'Diploma',
      image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Advanced office productivity', 'Applied computer workflows', 'Digital problem solving', 'Project-based practice'],
      audience: ['Graduates', 'Working learners', 'Career-focused students'],
      progression: 'Suitable for learners aiming for deeper professional or technical qualification.'
    },
    {
      code: 'TALLY PRIME',
      slug: 'tally-prime',
      name: 'Tally Prime',
      duration: 2,
      durationLabel: '2 Months',
      categoryPrimary: 'Accounting',
      categories: ['Certification', 'Accounting', 'Recommended'],
      shortDescription: 'Learn practical accounting processes and reporting using Tally Prime for business tasks.',
      description: 'This course introduces accounting operations, vouchers, ledgers and reports using Tally Prime in real business workflows.',
      eligibility: 'Open to beginners',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
      featured: true,
      recommended: true,
      modules: ['Accounting basics', 'Voucher entry and ledger work', 'Business reporting', 'Practical Tally exercises'],
      audience: ['Students', 'Office workers', 'Accounting beginners'],
      progression: 'A useful step toward more advanced accounting and finance study.'
    },
    {
      code: 'TALLY PROFESSIONAL',
      slug: 'tally-professional',
      name: 'Tally Professional',
      duration: 4,
      durationLabel: '4 Months',
      categoryPrimary: 'Accounting',
      categories: ['Certification', 'Accounting'],
      shortDescription: 'Strengthen accounting and reporting skills through practical Tally-based business workflows.',
      description: 'This higher-level course covers advanced accounting entries, inventory handling and business reporting in a practical training context.',
      eligibility: 'Basic accounting or Tally familiarity recommended',
      level: 'Intermediate',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Advanced accounting entries', 'Inventory and reporting', 'Business transaction practice', 'Practical accounting assignments'],
      audience: ['Accounting learners', 'Office staff', 'Business students'],
      progression: 'A route toward professional accounting understanding and office operations work.'
    },
    {
      code: 'GCC VAT',
      slug: 'gcc-vat',
      name: 'GCC VAT',
      duration: 1,
      durationLabel: '1 Month',
      categoryPrimary: 'Taxation',
      categories: ['Certification', 'Taxation'],
      shortDescription: 'Understand the basics of GCC VAT and simple tax-related business calculation methods.',
      description: 'This short course covers essential VAT concepts, basic calculation methods and practical documentation understanding for business learners.',
      eligibility: 'Suitable for beginners and working professionals',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['VAT concepts', 'Calculation basics', 'Business documentation', 'Practical examples'],
      audience: ['Business learners', 'Office staff', 'Professionals'],
      progression: 'Useful alongside accounting and general finance learning.'
    },
    {
      code: 'SAGA 50',
      slug: 'saga-50',
      name: 'SAGA 50',
      duration: 1,
      durationLabel: '1 Month',
      categoryPrimary: 'Accounting',
      categories: ['Certification', 'Accounting'],
      shortDescription: 'Explore business accounting basics using software-driven practical accounting methods.',
      description: 'This short course helps learners understand everyday accounting systems and software-based business record management for basic office tasks.',
      eligibility: 'Beginner friendly',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Business accounting basics', 'Software-based entry practice', 'Reports and summaries', 'Practical exercises'],
      audience: ['Students', 'Business beginners', 'Office learners'],
      progression: 'Useful as a starter before broader accounting or office programmes.'
    },
    {
      code: 'QUICK BOOKS',
      slug: 'quickbooks',
      name: 'QuickBooks',
      duration: 1,
      durationLabel: '1 Month',
      categoryPrimary: 'Accounting',
      categories: ['Certification', 'Accounting'],
      shortDescription: 'Learn bookkeeping basics and digital account handling using QuickBooks-style workflows.',
      description: 'This course introduces basic bookkeeping, transaction entries and business financial record management in a digital environment.',
      eligibility: 'Open to beginners',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Bookkeeping basics', 'Digital account entries', 'Financial reports and summaries', 'Record handling practice'],
      audience: ['Students', 'Office learners', 'Business beginners'],
      progression: 'Build confidence before moving to longer accounting and finance programmes.'
    },
    {
      code: 'PYTHON',
      slug: 'python',
      name: 'Python',
      duration: 2,
      durationLabel: '2 Months',
      categoryPrimary: 'Programming',
      categories: ['Certification', 'Programming', 'Recommended'],
      shortDescription: 'Learn Python basics, logic and beginner-level coding practice in a simple step-by-step format.',
      description: 'This beginner-friendly course introduces programming concepts, control flow, logic building and practical Python exercises.',
      eligibility: 'No prior programming experience required',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80',
      featured: true,
      recommended: true,
      modules: ['Programming logic', 'Variables and control structures', 'Python syntax', 'Simple coding exercises'],
      audience: ['Students', 'Beginners', 'Career starters'],
      progression: 'A strong entry point to software learning and broader IT study.'
    },
    {
      code: 'PYTHON BASE',
      slug: 'python-base',
      name: 'Python Base',
      duration: 1,
      durationLabel: '1 Month',
      categoryPrimary: 'Programming',
      categories: ['Certification', 'Programming'],
      shortDescription: 'A short introduction to Python fundamentals and beginner coding logic.',
      description: 'This introductory course makes the first steps in Python easy, covering fundamental syntax and simple problem-solving exercises.',
      eligibility: 'Beginner friendly',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Python syntax essentials', 'Logic building blocks', 'Simple coding tasks', 'Practical coding practice'],
      audience: ['Students', 'Beginners', 'Self-learners'],
      progression: 'A good start before longer programming or digital application study.'
    },
    {
      code: 'JAVA',
      slug: 'java',
      name: 'Java',
      duration: 1,
      durationLabel: '1 Month',
      categoryPrimary: 'Programming',
      categories: ['Certification', 'Programming'],
      shortDescription: 'Learn the core ideas of Java programming and beginner-level coding logic.',
      description: 'This short course introduces Java basics, object-oriented thinking and simple programming exercises for new learners.',
      eligibility: 'Suitable for beginners',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Java basics', 'Object-oriented thinking', 'Simple exercises', 'Basic problem solving'],
      audience: ['Students', 'Programming beginners', 'IT learners'],
      progression: 'Useful before deeper software or application learning.'
    },
    {
      code: 'C, C++',
      slug: 'c-and-c-plus-plus',
      name: 'C & C++',
      duration: 1,
      durationLabel: '1 Month',
      categoryPrimary: 'Programming',
      categories: ['Certification', 'Programming'],
      shortDescription: 'Understand core programming structure and logic using C and C++ lessons.',
      description: 'This short introduction builds basic programming understanding through syntax, logic and practical C and C++ exercises.',
      eligibility: 'Beginners welcome',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Programming basics', 'Control structures', 'Functions and logic', 'Simple coding practice'],
      audience: ['Students', 'Beginners', 'IT aspirants'],
      progression: 'Helpful preparation for deeper software and coding pathways.'
    },
    {
      code: 'MS EXCEL',
      slug: 'ms-excel',
      name: 'MS Excel',
      duration: 1,
      durationLabel: '1 Month',
      categoryPrimary: 'Office Productivity',
      categories: ['Certification', 'Office Productivity'],
      shortDescription: 'Learn spreadsheet basics, formulas and practical office reporting with Excel.',
      description: 'This course covers the main Excel features used in office work, including tables, formulas and simple reporting tasks.',
      eligibility: 'Beginner friendly',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Excel interface and navigation', 'Formula basics', 'Formatting and layout', 'Spreadsheet practice'],
      audience: ['Office learners', 'Students', 'Beginners'],
      progression: 'A practical foundation before advanced spreadsheet or data work.'
    },
    {
      code: 'ADVANCED EXCEL',
      slug: 'advanced-excel',
      name: 'Advanced Excel',
      duration: 2,
      durationLabel: '2 Months',
      categoryPrimary: 'Office Productivity',
      categories: ['Certification', 'Office Productivity', 'Recommended'],
      shortDescription: 'Move beyond the basics with advanced Excel formulas, data handling and reporting techniques.',
      description: 'This course builds practical Excel expertise for reports, charts, analysis and professional office productivity tasks.',
      eligibility: 'MS Excel basics recommended',
      level: 'Intermediate',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
      featured: true,
      recommended: true,
      modules: ['Advanced formulas', 'Data organisation and analysis', 'Reporting and dashboard basics', 'Practical spreadsheet tasks'],
      audience: ['Office staff', 'Students', 'Working learners'],
      progression: 'Useful for office roles requiring modern spreadsheet and reporting work.'
    },
    {
      code: 'POWER BI',
      slug: 'power-bi',
      name: 'Power BI',
      duration: 2,
      durationLabel: '2 Months',
      categoryPrimary: 'Data Analytics',
      categories: ['Certification', 'Data Analytics'],
      shortDescription: 'Learn business data visualisation and reporting with Power BI for practical analysis.',
      description: 'This course introduces Power BI fundamentals, dashboard creation and business reporting to interpret data more effectively.',
      eligibility: 'Basic Excel familiarity helpful',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Business data basics', 'Power BI interface', 'Charts and dashboards', 'Reporting workflow practice'],
      audience: ['Students', 'Office professionals', 'Data beginners'],
      progression: 'A step toward modern business analysis and reporting skills.'
    },
    {
      code: 'GST',
      slug: 'gst',
      name: 'GST',
      duration: 1,
      durationLabel: '1 Month',
      categoryPrimary: 'Taxation',
      categories: ['Certification', 'Taxation'],
      shortDescription: 'Understand GST basics and how tax concepts apply in daily business and accounting work.',
      description: 'This short course introduces GST principles, documentation basics and practical business-oriented understanding of tax tasks.',
      eligibility: 'Open to beginners',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['GST overview', 'Tax concepts', 'Business documentation basics', 'Practical examples'],
      audience: ['Business learners', 'Students', 'Office staff'],
      progression: 'Pairs well with accounting and finance study.'
    },
    {
      code: 'GRAPHIC DESIGNING',
      slug: 'graphic-designing',
      name: 'Graphic Designing',
      duration: 4,
      durationLabel: '4 Months',
      categoryPrimary: 'Graphic Design',
      categories: ['Certification', 'Graphic Design'],
      shortDescription: 'Develop design ideas, layout thinking and visual communication skills for digital and print work.',
      description: 'This course helps students learn the principles of design, digital composition and practical creative output for visual media.',
      eligibility: 'Beginner friendly',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
      featured: true,
      recommended: false,
      modules: ['Design principles', 'Colour and composition', 'Layout and poster design', 'Practical design assignments'],
      audience: ['Students', 'Creative learners', 'Beginners'],
      progression: 'A pathway to design, multimedia and creative digital careers.'
    },
    {
      code: 'PHOTOSHOP',
      slug: 'photoshop',
      name: 'Photoshop',
      duration: 2,
      durationLabel: '2 Months',
      categoryPrimary: 'Graphic Design',
      categories: ['Certification', 'Graphic Design'],
      shortDescription: 'Learn image editing, retouching and visual design techniques using Photoshop.',
      description: 'This course introduces Photoshop tools for editing photographs, preparing creative visuals and working with design layers and effects.',
      eligibility: 'Open to creative beginners',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Photoshop basics', 'Image editing and retouching', 'Design composition', 'Creative practical exercises'],
      audience: ['Creative learners', 'Students', 'Beginners'],
      progression: 'Useful before advanced design and publishing work.'
    },
    {
      code: 'ILLUSRATOR',
      slug: 'illustrator',
      name: 'Illustrator',
      duration: 2,
      durationLabel: '2 Months',
      categoryPrimary: 'Graphic Design',
      categories: ['Certification', 'Graphic Design'],
      shortDescription: 'Create vector graphics and polished design layouts using Illustrator tools.',
      description: 'This practical course focuses on vector illustration, graphic composition and visual asset creation for digital and print work.',
      eligibility: 'Suitable for beginners',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Illustrator fundamentals', 'Vector graphics', 'Creative asset design', 'Practical design tasks'],
      audience: ['Design learners', 'Students', 'Beginners'],
      progression: 'A strong companion to design and multimedia study.'
    },
    {
      code: 'MALAYALAM TYPING',
      slug: 'malayalam-typing',
      name: 'Malayalam Typing',
      duration: 1,
      durationLabel: '1 Month',
      categoryPrimary: 'Typing',
      categories: ['Certification', 'Typing'],
      shortDescription: 'Improve Malayalam typing speed, rhythm and keyboard familiarity for work and office tasks.',
      description: 'This course helps learners practise Malayalam typing with emphasis on speed, accuracy and practical office communication tasks.',
      eligibility: 'Beginner friendly',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Keyboard basics', 'Malayalam key placement', 'Speed and accuracy practice', 'Typing task drills'],
      audience: ['Students', 'Office workers', 'Beginners'],
      progression: 'Useful for office document work and digital communication tasks.'
    },
    {
      code: 'ENGLISH TYPING',
      slug: 'english-typing',
      name: 'English Typing',
      duration: 1,
      durationLabel: '1 Month',
      categoryPrimary: 'Typing',
      categories: ['Certification', 'Typing'],
      shortDescription: 'Build faster, cleaner English typing habits for office work and documentation tasks.',
      description: 'This short course strengthens typing speed, accuracy and office writing confidence for everyday digital work.',
      eligibility: 'Beginner friendly',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Typing fundamentals', 'Speed and accuracy', 'Office documents', 'Writing drills'],
      audience: ['Students', 'Office learners', 'Beginners'],
      progression: 'Useful before data entry, clerical and office workflow study.'
    },
    {
      code: 'OFFICE OPERATION',
      slug: 'office-operation',
      name: 'Office Operation',
      duration: 3,
      durationLabel: '3 Months',
      categoryPrimary: 'Office Operations',
      categories: ['Certification', 'Office Operations'],
      shortDescription: 'Understand daily office operations, filing practices and practical workplace administration.',
      description: 'This course introduces office routines, documentation methods and communication practices for administrative and clerical work.',
      eligibility: 'Open to beginners',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Office workflow basics', 'Filing and documentation', 'Communication and scheduling', 'Practical office routines'],
      audience: ['Students', 'Office staff', 'Beginners'],
      progression: 'Helpful for office roles and continued digital skills training.'
    },
    {
      code: 'BASIC',
      slug: 'basic',
      name: 'Basic',
      duration: 1,
      durationLabel: '1 Month',
      categoryPrimary: 'IT Basics',
      categories: ['Certification', 'IT Basics'],
      shortDescription: 'Build a simple, practical base in computer use and day-to-day digital skills.',
      description: 'This introductory course covers essential computer literacy, navigation and digital confidence for new learners.',
      eligibility: 'Beginner friendly',
      level: 'Beginner',
      type: 'Certification',
      image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Computer basics', 'System navigation', 'Digital safety', 'Basic office use'],
      audience: ['Students', 'Beginners', 'New learners'],
      progression: 'A foundation before more advanced digital or office programmes.'
    },
    {
      code: 'FOUNDATION ENHANCEMENT',
      slug: 'foundation-enhancement',
      name: 'Foundation Enhancement',
      duration: 1,
      durationLabel: '1 Month',
      categoryPrimary: 'Foundation',
      categories: ['Certificate', 'Foundation'],
      shortDescription: 'Strengthen core digital readiness and learning confidence for learners starting their IT journey.',
      description: 'This foundation-focused module helps students improve digital confidence, basic computer awareness and learning readiness before taking higher-level courses.',
      eligibility: 'Beginner friendly',
      level: 'Beginner',
      type: 'Certificate',
      image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
      featured: false,
      recommended: false,
      modules: ['Digital readiness', 'Basic computer confidence', 'Learning support and practice', 'Foundation skill reinforcement'],
      audience: ['New learners', 'Students', 'Beginners'],
      progression: 'A stepping stone toward office, application and technical training.'
    }
  ],
  gallery: [
    { title: 'Classroom learning', category: 'Classes', image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80' },
    { title: 'Practical session', category: 'Activities', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80' },
    { title: 'Workshop discussion', category: 'Workshops', image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80' },
    { title: 'Hands-on training', category: 'Students', image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80' },
    { title: 'Digital learning environment', category: 'Institute', image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80' },
    { title: 'Student support', category: 'Activities', image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80' },
    { title: 'Learning together', category: 'Classes', image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80' },
    { title: 'Creative workshop', category: 'Workshops', image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80' }
  ]
};
